import streamlit as st
import joblib
import pandas as pd

# Load trained Random Forest model
model = joblib.load("models/best_model.joblib")

st.set_page_config(
    page_title="Heart Disease Prediction",
    layout="centered"
)

st.title("Heart Disease Prediction")
st.write("Enter the patient information below to obtain a model prediction.")

st.subheader("Patient Information")

# Patient inputs
thal = st.selectbox(
    "Thal",
    [3, 6, 7],
    format_func=lambda x: {
        3: "3 - Normal",
        6: "6 - Fixed defect",
        7: "7 - Reversible defect"
    }[x]
)

cp = st.selectbox(
    "Chest Pain Type",
    [1, 2, 3, 4],
    format_func=lambda x: {
        1: "1 - Typical angina",
        2: "2 - Atypical angina",
        3: "3 - Non-anginal pain",
        4: "4 - Asymptomatic"
    }[x]
)

thalach = st.number_input(
    "Maximum Heart Rate",
    min_value=50,
    max_value=250,
    value=150
)

exang = st.selectbox(
    "Exercise-Induced Angina",
    [0, 1],
    format_func=lambda x: "0 - Not present" if x == 0 else "1 - Present"
)

sex = st.selectbox(
    "Sex",
    [0, 1],
    format_func=lambda x: "0 - Female" if x == 0 else "1 - Male"
)

slope = st.selectbox(
    "ST Slope",
    [1, 2, 3],
    format_func=lambda x: {
        1: "1 - Upsloping",
        2: "2 - Flat",
        3: "3 - Downsloping"
    }[x]
)

chol = st.number_input(
    "Cholesterol (mg/dL)",
    min_value=50,
    max_value=700,
    value=200
)

oldpeak = st.number_input(
    "Oldpeak",
    min_value=0.0,
    max_value=10.0,
    value=1.0,
    step=0.1
)

age = st.number_input(
    "Age",
    min_value=1,
    max_value=120,
    value=50
)

ca = st.number_input(
    "Number of Major Vessels",
    min_value=0,
    max_value=4,
    value=0,
    step=1
)

# Prediction
if st.button("Predict Heart Disease"):

    # Same feature order as predict.py
    patient = pd.DataFrame([{
        "thal": thal,
        "cp": cp,
        "thalach": thalach,
        "exang": exang,
        "sex": sex,
        "slope": slope,
        "chol": chol,
        "oldpeak": oldpeak,
        "age": age,
        "ca": ca
    }])

    prediction = model.predict(patient)[0]
    probability = model.predict_proba(patient)[0]

    no_disease = probability[0] * 100
    disease = probability[1] * 100

    st.subheader("Prediction Result")

    if prediction == 0:
        st.success("Prediction: No Heart Disease")
    else:
        st.error("Prediction: Heart Disease")

    st.write(f"No Heart Disease: {no_disease:.2f}%")
    st.write(f"Heart Disease: {disease:.2f}%")

    st.info(
        "This prediction is generated by the trained Random Forest "
        "model and does not independently diagnose heart disease."
    )
